name: "This isn't working"
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6b6265'
    - '#81a3d1'
    - '#27241f'
    - '#c1cfec'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
