name: "This isn't working"
favicon: null
layout_spectrum: 0.036592668388038874
typography_spectrum: 0.7371441852301359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
